apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: microservices
type: Opaque
stringData:
  .env.dev: |
    ORDER_DB_URL=jdbc:postgresql://postgres:5432/eks-setup-db?currentSchema=product_service
    ORDER_DB_USERNAME=<YOUR_DB_USERNAME>
    ORDER_DB_PASSWORD=<YOUR_DB_PASSWORD>

