server:
  port: 8084
spring:
  application:
    name: order-service
  config:
    import:
      - optional:file:${APP_CONFIG_PATH}/application-${spring.profiles.active}.yml
      - optional:file:${APP_CONFIG_PATH}/order-service.yml
      - optional:file:${APP_SECRETS_PATH}/.env.${spring.profiles.active}[.properties]
      - optional:file:${APP_SECRETS_PATH}/order-service/.env.${spring.profiles.active}[.properties]
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway