apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: auth-service:1.0

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev

            - name: APP_CONFIG_PATH
              value: /app/config
            - name: APP_SECRETS_PATH
              value: /app/secrets

          volumeMounts:
            - name: auth-config
              mountPath: /app/config

            - name: auth-secret
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: auth-config
          configMap:
            name: auth-config

        - name: auth-secret
          secret:
            secretName: auth-secret
