apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: microservices
type: Opaque
stringData:
  .env.dev: |
    AUTH_DB_URL=jdbc:postgresql://postgres:5432/eks-setup-db?currentSchema=auth_service
    AUTH_DB_USERNAME=<YOUR_DB_USERNAME>
    AUTH_DB_PASSWORD=<YOUR_DB_PASSWORD>
    JWT_SECRET=<YOUR_JWT_SECRET>