server:
  port: 8082

spring:
  application:
    name: auth-service

  config:
    import:
      - optional:file:${APP_CONFIG_PATH}/application-${spring.profiles.active}.yml
      - optional:file:${APP_CONFIG_PATH}/auth-service.yml
      - optional:file:${APP_SECRETS_PATH}/.env.${spring.profiles.active}[.properties]
      - optional:file:${APP_SECRETS_PATH}/auth-service/.env.${spring.profiles.active}[.properties]