apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gateway-service

  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      containers:
        - name: gateway-service
          image: gateway-service:1.0

          ports:
            - containerPort: 8080

          env:
              - name: SPRING_PROFILES_ACTIVE
                value: dev

              - name: APP_CONFIG_PATH
                value: /app/config
              - name: APP_SECRETS_PATH
                value: /app/secrets

          volumeMounts:
            - name: gateway-config
              mountPath: /app/config

            - name: gateway-secret
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: gateway-config
          configMap:
            name: gateway-config

        - name: gateway-secret
          secret:
            secretName: gateway-secret 