apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: microservices
type: Opaque
stringData:
  .env.dev: |
    AUTH_SERVICE_URL=http://auth-service:8082
    PRODUCT_SERVICE_URL=http://product-service:8083
    ORDER_SERVICE_URL=http://order-service:8084