server:
  port: 8083
spring:
  application:
    name: product-service
  config:
    import:
      - optional:file:${APP_CONFIG_PATH}/application-${spring.profiles.active}.yml
      - optional:file:${APP_CONFIG_PATH}/product-service.yml
      - optional:file:${APP_SECRETS_PATH}/.env.${spring.profiles.active}[.properties]
      - optional:file:${APP_SECRETS_PATH}/product-service/.env.${spring.profiles.active}[.properties]
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway