apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: microservices
type: Opaque
stringData:
  .env.dev: |
    PRODUCT_DB_URL=jdbc:postgresql://postgres:5432/eks-setup-db?currentSchema=product_service
    PRODUCT_DB_USERNAME=<YOUR_DB_USERNAME>
    PRODUCT_DB_PASSWORD=<YOUR_DB_PASSWORD>

