apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_DB: <YOUR_DB_NAME>
  POSTGRES_USER: <YOUR_DB_USER
  POSTGRES_PASSWORD: <YOUR_DB_PASSWORD>