server:
  port: 8080
spring:
  application:
    name: api-gateway

  config:
    import:
      - optional:file:${APP_CONFIG_PATH}/application-${spring.profiles.active}.yml
      - file:${APP_CONFIG_PATH}/api-gateway.yml
      - optional:file:${APP_SECRETS_PATH}/.env.${spring.profiles.active}[.properties]
      - optional:file:${APP_SECRETS_PATH}/api-gateway/.env.${spring.profiles.active}[.properties]