server:
  port: 8080
spring:
  application:
    name: api-gateway

  config:
    import:
      - optional:file:E:/EKS-Deploy/eks-configs/application-${spring.profiles.active}.yml
      - file:E:/EKS-Deploy/eks-configs/api-gateway.yml
      - optional:file:E:/EKS-Deploy/eks-secrets/.env.${spring.profiles.active}[.properties]
      - optional:file:E:/EKS-Deploy/eks-secrets/api-gateway/.env.${spring.profiles.active}[.properties]